PrimeVideoClone/Accounts/urls.py
from django.urls import path , include
from . import views

app_name = "Accounts"
urlpatterns = [
    path('signup/',views.signup_view, name="signup"),
    path('login/',views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('profile/', views.profile_view, name="profile"),
]

PrimeVideoClone/Help/urls.py
from django.urls import path , include
from . import views

app_name = "Help"
urlpatterns = [
    path('',views.help_home, name="help_home"),
    # path('signup/',views.signup_view, name="signup"),
    # path('login/',views.login_view, name="login"),
    # path('logout/', views.logout_view, name="logout"),
    # path('register/', views.register_view, name="register"),
    # path('profile/', views.profile_view, name="profile"),
]

PrimeVideoClone/PrimeVideoClone/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = "PrimeVideoClone"

urlpatterns = [
    path('', views.home_view, name='home'),
	path('Accounts/', include('Accounts.urls')),
	path('Help/', include('Help.urls')),
    path('admin/', admin.site.urls),
]

PrimeVideoClone/Accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
	Username = models.OneToOneField(User, default=None, on_delete=models.PROTECT)
	First_Name = models.CharField(max_length=100)
	Last_Name = models.CharField(max_length=100)
	Email_Address = models.EmailField()
	Age = models.IntegerField(default='18')
	#Date_Of_Birth = models.DateTimeField()
	Profile_Pic =  models.ImageField(upload_to='ProfilePics/',default='ProfilePics/default.jpg',blank=True, null=True)    

	def __str__(self):
		return self.First_Name + " " + self.Last_Name +"\t" +self.Email_Address

	def delete(self, *args, **kwargs):
		self.Profile_Pic.delete()
		super().delete(*args, **kwargs)

	# def save(self):
	# 	super().save()
	# 	img = Image.open(self.image.path)
	# 	if img.height > 300 or img.width > 300:
	# 		output_size = (300, 300)
	# 		img.thumbnail(output_size)
	# 		img.save(self.image.path)

PrimeVideoClone/Help/models.py
from django.db import models

# Create your models here.

PrimeVideoClone/Accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class CreateProfile(forms.ModelForm):
	class Meta:
		model = models.Profile
		fields = ['First_Name', 'Last_Name', 'Age', 'Profile_Pic']

class UpdateProfile(forms.ModelForm):
	class Meta:
		model = models.Profile
		fields = ['First_Name', 'Last_Name', 'Age', 'Profile_Pic']

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
    	model = User
    	fields = ['username', 'email', 'password1', 'password2']

PrimeVideoClone/Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import  AuthenticationForm
from . import forms
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
         form = forms.UserRegisterForm(request.POST)
         if form.is_valid():
             user = form.save()
             login(request, user)
             return redirect('Accounts:register')
    else:
    	form = forms.UserRegisterForm()
    return render(request, 'Accounts/signup.html', { 'form': form })

@login_required(login_url="/Accounts/login/")
def register_view(request):
    if request.method == "POST":
        form = forms.CreateProfile(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.Username = request.user
            instance.Email_Address = request.user.email 
            instance.save()
            return redirect('Accounts:login')
    else:
        form = forms.CreateProfile()
    return render(request, 'Accounts/register.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else: 
                return redirect('Accounts:profile')
    else:
    	form = AuthenticationForm()
    return render(request, 'Accounts/login.html', { 'form': form })

@login_required(login_url="/Accounts/login/")
def profile_view(request):
    return render(request, 'Accounts/profile.html')

@login_required(login_url="/Accounts/login/")
def logout_view(request):
	logout(request)
	return redirect('home')

PrimeVideoClone/Help/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect

# Create your views here.
def help_home(request):
	return render(request, 'Help/home.html')

PrimeVideoClone/PrimeVideoClone/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect

# Create your views here.
def home_view(request):
	return render(request, 'homePage.html')

PrimeVideoClone/Accounts/templates/Accounts/login.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row" style="padding:10%;">
    <div class='col-3'>
    </div>
    <div class='col-6'>
        <h1>Log in</h1>
        <form class="site-form" action="{% url 'Accounts:login' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <input type="submit" value="Login" />
        </form>
        <p>Not got an account? <a href="{% url 'Accounts:signup' %}">Sign Up</a></p>
    </div>
    <div class='col-3'>
    </div>
</div>
{% endblock %}	

PrimeVideoClone/Accounts/templates/Accounts/profile.html
{% extends 'base_layout.html' %}


{% block content %}
{% block updateProfile %}
{% endblock %}
       
       <div class="profile-detail">           
           <div class="profile"> 
             <img src="{{ user.profile.Profile_Pic.url }}"/>
                <h2>Profile of    {{ user.profile.Username }}</h2>
                <p>Name:  {{ user.profile.First_Name}}&nbsp;{{user.profile.Last_Name }}</p>
                <p>Email Address:  {{ user.profile.Email_Address }}</p>
                <p>Age:  {{ user.profile.Age }}</p>
           </div> 
           {% if request.path == "/accounts/profile/" %}
           	<div class="update">
        	</div>
           {% endif %}
       </div>
       
{% endblock %}

PrimeVideoClone/Accounts/templates/Accounts/register.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row" style="padding:5%;">
    <div class='col-3'>
    </div>
    <div class='col-6'>
        <h1>Register</h1>
      	<form class="site-form" action="{% url 'Accounts:register' %}" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
        	{{ form|crispy}}
        	<input type="submit" name="submit">
      	</form>
    </div>
    <div class='col-3'>
    </div>
</div>
{% endblock %}

PrimeVideoClone/Accounts/templates/Accounts/signup.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row" style="padding:5%;">
    <div class='col-3'>
    </div>
    <div class='col-6'>
      <h1>Sign Up</h1>
      <form class="site-form" action="{% url 'Accounts:signup' %}" method="post">
      	{% csrf_token %}
      	{{ form|crispy }}
      	<input type="submit" name="submit">
      </form>
  </div>
</div>
{% endblock %}

PrimeVideoClone/Help/templates/Help/home.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
<!-- f2f4f6 -->
{% block content %}
<div class="row bg-dark">
    <div class='col-5'>
    </div>
    <div class='col-2'>
        <div style="color:#f2f4f6;"><h1>Help</h1></div>
    </div>
    <div class='col-5'>
    </div>
</div>
<div class="row">
    <div class='col-1'>
    </div>
    <div class='col-4'>
        <div class="row">
            <h1>Setting Up Prime Video</h1>
            <ul>
                <li>Install Prime Video on Your Devices</li>
                <li>Is Prime Video Included with Amazon Prime?</li>
                <li>Watch Prime Video on Chromecast</li>
                <li>Download Prime Video Titles</li>
                <li>Parental Controls on Prime Video</li>
                <li>Set up a Prime Video PIN</li>
                <li>Set up Restrictions on Prime Video</li>
                <li>Receive Twitch Prime Benefits</li>
                <li>About Prime Video Promotional Pricing</li>
                <li>Amazon Maturity Ratings</li>
                <li>Cancel My Prime Video Subscription</li>
            </ul>
        </div>
        <div class="row">
            <h1>Troubleshooting</h1>
            <ul>
                <li>Issues While Playing Prime Video Titles</li>
                <li>Issues with Prime Video Payment and Order Errors</li>
                <li>Issues with Prime Video PIN Errors</li>
                <li>Issues during Sign In or Sign Out on Prime Video</li>
                <li>Changes to Prime Video Subscriptions for Brazil</li>
                <li>Can I Watch Prime Video If I Travel Abroad?</li>
            </ul>
        </div>
    </div>
    <div class='col-1'>
    </div>
    <div class='col-4'>
        <div class="row">
                <h1>    Prime Video Channels</h1>
                <ul>
                    <li>What Is Included with Prime Video Channels?</li>
                    <li>Why Do I Have to Pay Extra for Prime Video Channels?</li>
                    <li>Problem Watching Prime Video Channels While I Travel</li>
                    <li>Issues Accessing Channel Subscriptions from External Providers</li>
                    <li>Cancel Your Prime Video Channel Subscription</li>
                </ul>
        </div>
        <div class="row">
                <h1> Supported Devices </h1>
                <ul>
                    <li>Smart TVs with the Prime Video App</li>
                    <li>Amazon Devices with the Prime Video App</li>
                    <li>Mobile Devices with the Prime Video App</li>
                    <li>Games Consoles with the Prime Video App</li>
                    <li>Blu-Ray Players with the Prime Video App</li>
                    <li>Set Top Boxes and Media Players with the Prime Video App</li>
                    <li>Prime Video System Requirements for Computers</li>
                </ul>
        </div>
        <div class="row">
                <h1> Terms & Conditions </h1>
                <ul>
                    <li>VAT / GST Rates</li>
                    <li>About Tax on Prime Video subscriptions sold on PrimeVideo.com </li>
                    <li>Amazon Prime Video Service Provider Information and Applicable Terms and Policies</li>
                </ul>
        </div>
    </div>
</div>
{% endblock %}	

PrimeVideoClone/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Prime Video Clone</title>
        
        <link href="{% static '/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-light navbar-light">
                <!-- Brand -->
                <a class = "navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'primelogo.png' %}" alt="Prime Video " />
                </a>
                <!-- Links -->
                <ul class="nav navbar-nav ml-auto" style="padding-right: 7%;">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <form class="form-inline float-right" action="#">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                                <button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </li>                        
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><i class="fa fa-2x fa-user" aria-hidden="true"></i></a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
                            <a class="dropdown-item" href="{% url 'Help:help_home' %}"><i class="fa fa-question-circle" aria-hidden="true"></i> Help</a>
                            {% if user.is_authenticated %}
                                    <a class="dropdown-item" href="{% url 'Accounts:profile' %}"><i class="fa fa-user" aria-hidden="true"></i> Profile</a>
                                    <a class="dropdown-item" href="{% url 'Accounts:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout </a>
                            {% else %}
                                    <a class="dropdown-item" href="{% url 'Accounts:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
                                    <a class="dropdown-item" href="{% url 'Accounts:signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Signup</a>
                            {% endif %}
                            
                        </div>
                    </li>        
                </ul>
              </nav>
        <!-- <div class="container" style="width: 100%;"> -->
            {% block content %}
            {% endblock %}
        <!-- </div> -->
    </body>
</html>

PrimeVideoClone/templates/homePage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="HomeBackground1" style="width:99% ; height:660px">
	<div class="row" style="padding:5% 0% 0% 5% ;"> <!-- top right bottom left -->
	    <div class='col-4 text-white'>
	    	<div class="row " style="padding:5%;">
				<h1>Welcome to Prime Video </h1>    	
			</div>
	    	<div class="row" style="padding:5%;">
				<p>Join Prime to watch the latest movies, exclusive TV shows as well as award-winning Amazon Originals.
				</p>
	    	</div>
	    	<div class="row" style="padding:5%;">
	 		<p>
	 			Start your 30-day free trial <br>
				With any credit card or select debit cards 
			</p>
	    	</div>
	    	<div class="row" style="padding:5%;">
	    		<p>
	    		 	Join Prime at ₹129 per month <br>
	    			With any credit card or select debit cards 
	    		</p>
	    	</div>
	    </div>
	</div>
</div>
<div class="HomeBackground2" style="width:99% ; height:660px">
	<div class="row" style="padding-top: 5%;">
		<div class="col-7">
		</div>
		<div class="col-4">
			<div class="row" style="padding-top: 10%;">
					<h1 class="text-center text-white"> Get ₹500 cashback on 1-year prime membership of ₹999 </h1>
			</div>
			<div class="row" style="padding-top: 10%;">
					<h3 class="text-center text-white"> To be eligible for the offer, you must be between 18-24 years old.<br><br>
					<button class="btn btn-success text-center "> Know more</button>
					</h3>
			</div>
		</div>
	</div>
</div>
<div class="HomeBackground3" style="width:99% ; height:660px">
	<div class="row">
		<div class="col-5">
			<div class="row" style="padding-top: 10%; padding-left: 10%;">
					<h1 class="text-center text-white">One membership, Many benefits</h1>
			</div>
			<div class="row" style="padding-top: 10%; padding-left: 10%;">
						<h3 class="text-center text-white">  Your Prime membership now also includes ad-free music along with unlimited free, fast delivery on eligible items, exclusive access to deals & more. 
								<br>
								<br>
								<button class="btn btn-success text-center "> Get Started</button>
					</h3>
			</div>
		</div>
	</div>
</div>
{% endblock %}	